version: "3.8"

services:
  kali:
    build: ./kali
    image: kali-db:latest
    container_name: kali
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-msf}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-msfpass}
      POSTGRES_DB: ${POSTGRES_DB:-msf}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data/pgdata
      - ./volumes/kali_home:/root
    ports:
      - "127.0.0.1:5432:5432"   # optional: bind DB to host localhost only
    networks:
      - labnet
    tty: true
    stdin_open: true

  metasploit:
    build: ./metasploit
    image: metasploit-custom:latest
    container_name: metasploit
    depends_on:
      - kali
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-kali}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-msf}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-msfpass}
      POSTGRES_DB: ${POSTGRES_DB:-msf}
      MSF_MODE: ${MSF_MODE:-console}   # console | rpc | shell
      MSFDB_INIT: "false"
    volumes:
      - ./volumes/msfdata:/root/.msf4
    networks:
      - labnet
    tty: true
    stdin_open: true

networks:
  labnet:
    driver: bridge
